-- Plain-English archetype enrichments (generated by @colenso/enrichment-core)
-- One row per F-tag archetype. Record pages JOIN on archetype_key and
-- interpolate their own counts/dates/scope — no per-facility prose stored.
CREATE TABLE IF NOT EXISTS archetype_enrichment (
  archetype_key   TEXT PRIMARY KEY,  -- 'F0689'
  domain          TEXT NOT NULL DEFAULT 'nhg',
  plain_name      TEXT NOT NULL,
  explainer       TEXT NOT NULL,     -- 60-90 words, linter-enforced
  severity_context TEXT,
  action_prompts  TEXT,              -- JSON array: tour questions
  prompt_version  TEXT NOT NULL,
  review_status   TEXT NOT NULL DEFAULT 'draft',  -- draft|approved|flagged
  model           TEXT NOT NULL,
  generated_at    TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_archetype_review ON archetype_enrichment(review_status);

-- Phase 1: CMS occasionally renumbers F-tags; keep old keys resolving.
ALTER TABLE archetype_enrichment ADD COLUMN alias_of TEXT;
