// One-off asset generator: rasterizes the branded OG SVG (src/og-svg.ts) into
// a PNG so social platforms that don't render SVG previews (Twitter/X,
// Facebook, LinkedIn) get a real raster image. Writes a copy to public/og.png
// for reference and to src/og-png.generated.ts (base64) for the Worker to
// serve at /og.png, since this Worker has no static-assets binding.
// Run with: npx tsx scripts/generate-og-image.ts
import sharp from "sharp";
import { writeFileSync } from "node:fs";
import { OG_SVG } from "../src/og-svg";

async function main() {
  const png = await sharp(Buffer.from(OG_SVG)).png().toBuffer();
  writeFileSync("public/og.png", png);

  const base64 = png.toString("base64");
  const source = `// Generated by scripts/generate-og-image.ts. Do not edit by hand.\nexport const OG_PNG_BASE64 = "${base64}";\n`;
  writeFileSync("src/og-png.generated.ts", source);

  console.log(`Wrote public/og.png and src/og-png.generated.ts (${png.length} bytes)`);
}

main();
