/**
 * Import enrichments generated by enrichment-core into D1.
 *
 *   npx tsx scripts/import-enrichments.ts path/to/nhg.enrichments.jsonl [--remote]
 *
 * Only rows with zero lint issues are imported; flagged rows are skipped
 * loudly. Imported rows land as review_status='draft' — human signoff
 * flips them to 'approved' (see IMPLEMENTATION.md review loop).
 */
import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

const args = process.argv.slice(2);
const file = args.find((a) => !a.startsWith('--'));
if (!file) throw new Error('usage: import-enrichments.ts <file.jsonl> [--remote]');
const remote = args.includes('--remote');

const wranglerToml = readFileSync('wrangler.toml', 'utf8');
const dbName = wranglerToml.match(/database_name\s*=\s*"([^"]+)"/)?.[1];
if (!dbName) throw new Error('database_name not found in wrangler.toml');

interface Row {
  archetype_key: string; domain: string; plain_name: string;
  explainer: string; severity_context?: string; action_prompts: string[];
  prompt_version: string; model: string; generated_at: string;
  lint_issues: Array<{ rule: string }>;
}

const lines = readFileSync(file, 'utf8').trim().split('\n').map((l) => JSON.parse(l) as Row);
const clean = lines.filter((r) => r.lint_issues.length === 0);
const flagged = lines.length - clean.length;
if (flagged > 0) console.warn(`Skipping ${flagged} lint-flagged rows.`);

const esc = (s: string) => `'${s.replace(/'/g, "''")}'`;
const statements = clean.map((r) =>
  `INSERT OR REPLACE INTO archetype_enrichment
   (archetype_key, domain, plain_name, explainer, severity_context,
    action_prompts, prompt_version, review_status, model, generated_at)
   VALUES (${esc(r.archetype_key)}, ${esc(r.domain)}, ${esc(r.plain_name)},
   ${esc(r.explainer)}, ${r.severity_context ? esc(r.severity_context) : 'NULL'},
   ${esc(JSON.stringify(r.action_prompts))}, ${esc(r.prompt_version)},
   'draft', ${esc(r.model)}, ${esc(r.generated_at)});`
);

// Batch through wrangler d1 execute to stay under command-size limits.
const BATCH = 25;
for (let i = 0; i < statements.length; i += BATCH) {
  const chunk = statements.slice(i, i + BATCH).join('\n');
  execSync(
    `npx wrangler d1 execute ${dbName} ${remote ? '--remote' : '--local'} --command ${JSON.stringify(chunk)}`,
    { stdio: 'inherit' },
  );
}
console.log(`Imported ${clean.length} enrichments into ${dbName} (${remote ? 'remote' : 'local'}) as draft.`);
